// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1bl3_3H_W7BmKj2QzxLXnptw4sPmrv90',
    appId: '1:969830282573:web:57d2187fbe34feeb18b304',
    messagingSenderId: '969830282573',
    projectId: 'zoomclone-1891e',
    authDomain: 'zoomclone-1891e.firebaseapp.com',
    storageBucket: 'zoomclone-1891e.firebasestorage.app',
    measurementId: 'G-338VM7DCC3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLgzuKmum3JmjCzNpOvkadRptZL-WokYw',
    appId: '1:969830282573:android:77bcbb4a4cc197db18b304',
    messagingSenderId: '969830282573',
    projectId: 'zoomclone-1891e',
    storageBucket: 'zoomclone-1891e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyC6Asrm0OFzP2tNz-R5_td_v2_Fz6ZqA',
    appId: '1:969830282573:ios:06b6ecc0b17dac4f18b304',
    messagingSenderId: '969830282573',
    projectId: 'zoomclone-1891e',
    storageBucket: 'zoomclone-1891e.firebasestorage.app',
    iosBundleId: 'com.example.zoomclone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyC6Asrm0OFzP2tNz-R5_td_v2_Fz6ZqA',
    appId: '1:969830282573:ios:06b6ecc0b17dac4f18b304',
    messagingSenderId: '969830282573',
    projectId: 'zoomclone-1891e',
    storageBucket: 'zoomclone-1891e.firebasestorage.app',
    iosBundleId: 'com.example.zoomclone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1bl3_3H_W7BmKj2QzxLXnptw4sPmrv90',
    appId: '1:969830282573:web:9f68f9c71ce03eef18b304',
    messagingSenderId: '969830282573',
    projectId: 'zoomclone-1891e',
    authDomain: 'zoomclone-1891e.firebaseapp.com',
    storageBucket: 'zoomclone-1891e.firebasestorage.app',
    measurementId: 'G-6S2V3Y2YHT',
  );
}
